### PR TITLE
Bring 'Development' branch up to date with master

### PR DESCRIPTION
**Pull request by lewismc**
This PR merely forward ports everything from master to development branch such that we can continue with the AvroRPC stuff as well as some of the new work which has been slated for OODT.

### CODE REVIEW

**Comment by lewismc** [comment]
Note, tests are not stable IIRC.

**Comment by chrismattmann** [comment]
LGTM let's merge this to the development branch.

**Comment by lewismc** [comment]
done

**Comment by lewismc** [comment]
From now on, anything going in to master should be forward ported here. We can also work on fixing the many failing tests for ```development```

**Pull request merged**
