### PR TITLE
OODT-966 agility broken syntax under Python 3.X

### PR DESCRIPTION
**Pull request by lewismc**
Hi @nutjob4life tagging you here FYI. This issue is primarily meant to address https://issues.apache.org/jira/browse/OODT-966 but as you can see it quickly got out of control when attempting to upgrade agility to be used with Python 3.X
Several failing tests, i will have a look when I get more time.
Lewis

### CODE REVIEW

**Comment by chrismattmann** [comment]
@lewismc do you have a full fix for this yet?

**Comment by lewismc** [comment]
@chrismattmann no I got derailed as my requirements changed away from Python. I won't be putting any time into this any time really soon but I would like to come back and fix the tests at least.

**Comment by chrismattmann** [comment]
ack got it @lewismc is it ok then to close this and if you get time to fix the tests, open a new one?

**Comment by lewismc** [comment]
Yep, I have the branch locally so will make an attempt to revisit it reasonably soon.

**Pull request closed without merging**
