### PR TITLE
OODT-925 Update schema.xml field definitions for SOLR 5.X

### PR DESCRIPTION
**Pull request by lewismc**
This issue addresses https://issues.apache.org/jira/browse/OODT-925
The patch 
 * removes all obsolete, non-backwards compatible fieldType's classes such as solr.IntField, LongField, FloatField, DoubleField and DateField. The Trie versions should now be used
 * removes all 'enablePositionIncrements="true" ' parameter entries which are no longer used in Solr 5.X
 * Removes all examples for different languages (generally ordered by ISO code) due to the absence of the relevant required stopwords files. These should be added and defined on a use-case basis.

### CODE REVIEW

**Comment by lewismc** [comment]
Evidence of this patch being used is below
```
lmcgibbn@LMC-032857 /usr/local/solr-5.4.0 $ ./bin/solr -e cloud

Welcome to the SolrCloud example!

This interactive session will help you launch a SolrCloud cluster on your local workstation.
To begin, how many Solr nodes would you like to run in your local cluster? (specify 1-4 nodes) [2]:

Ok, let's start up 2 Solr nodes for your example SolrCloud cluster.
Please enter the port for node1 [8983]:

Please enter the port for node2 [7574]:

Creating Solr home directory /usr/local/solr-5.4.0/example/cloud/node1/solr
Cloning /usr/local/solr-5.4.0/example/cloud/node1 into
   /usr/local/solr-5.4.0/example/cloud/node2

Starting up Solr on port 8983 using command:
bin/solr start -cloud -p 8983 -s "example/cloud/node1/solr"

Waiting up to 30 seconds to see Solr running on port 8983 [/]
Started Solr server on port 8983 (pid=6739). Happy searching!


Starting up Solr on port 7574 using command:
bin/solr start -cloud -p 7574 -s "example/cloud/node2/solr" -z localhost:9983

Waiting up to 30 seconds to see Solr running on port 7574 [/]
Started Solr server on port 7574 (pid=6839). Happy searching!


Now let's create a new collection for indexing documents in your 2-node cluster.
Please provide a name for your new collection: [gettingstarted]
oodt
How many shards would you like to split oodt into? [2]

How many replicas per shard would you like to create? [2]

Please choose a configuration for the oodt collection, available options are:
basic_configs, data_driven_schema_configs, or sample_techproducts_configs [data_driven_schema_configs]
basic_configs

Connecting to ZooKeeper at localhost:9983 ...
Uploading /usr/local/solr-5.4.0/server/solr/configsets/basic_configs/conf for config oodt to ZooKeeper at localhost:9983

Creating new collection 'oodt' using command:
http://localhost:8983/solr/admin/collections?action=CREATE&name=oodt&numShards=2&replicationFactor=2&maxShardsPerNode=2&collection.configName=oodt

{
  "responseHeader":{
    "status":0,
    "QTime":3773},
  "success":{"":{
      "responseHeader":{
        "status":0,
        "QTime":3534},
      "core":"oodt_shard2_replica2"}}}

Enabling auto soft-commits with maxTime 3 secs using the Config API

POSTing request to Config API: http://localhost:8983/solr/oodt/config
{"set-property":{"updateHandler.autoSoftCommit.maxTime":"3000"}}
Successfully set-property updateHandler.autoSoftCommit.maxTime to 3000


SolrCloud example running, please visit: http://localhost:8983/solr
```

**Comment by lewismc** [comment]
Any objections to commit?

**Comment by lewismc** [comment]
Anyone able to test this patch out?

**Comment by chrismattmann** [comment]
@lewismc I don't have a Solr5 install, but I am +1 on reviewing the patch looks clean. One question I have - does this maintain back compat with Solr4 schema? If not, I'd like us to keep a schema4.xml and schema5.xml file. Make sense?

**Comment by lewismc** [comment]
bq. One question I have - does this maintain back compat with Solr4 schema?

No. I'll resend a PR which achieves this though. Good shout.

**Comment by lewismc** [comment]
I screwed this PR up, please refer to https://github.com/apache/oodt/pull/38

**Pull request closed without merging**
