### PR TITLE
[OODT-999] Fix for "File.toURL fails when their are spaces in project/repository paths"

### PR DESCRIPTION
**Pull request by madhawav**
Fix for https://issues.apache.org/jira/projects/OODT/issues/OODT-999
1) Modified unit tests involving data repository path to expose the issue.
2) Replaced the deprecated method File.toURL() which causes the issue by File.toURI().toURL().

### CODE REVIEW

**Comment by buggtb** [comment]
Good PR, nothing wrong that I can see and I've hit the encoding issues before so +1 from me.

**Comment by madhawav** [comment]
Thank you @buggtb @chrismattmann

**Comment by IMS94** [comment]
@chrismattmann Can this be merged?

**Comment by chrismattmann** [comment]
yep! merged

**Pull request merged**
