### PR TITLE
Added RegEx Exclude Comparator

### PR DESCRIPTION
**Pull request by karanjeets**
This Comparator takes Regular Expression as input and compare it with the absolute path of data file. Returns 0 if match found, else 1.

### CODE REVIEW

**Comment by buggtb** [comment]
Hi,

Is there a Jira ticket associated with this addition?

Tom

**Comment by karanjeets** [comment]
No Tom. This addition is based on a DRAT Issue - https://github.com/chrismattmann/drat/issues/19

Regards,
Karan

**Comment by buggtb** [comment]
Okay, can you please file an OODT jira at issues.apache.org and update CHANGES.txt so we can track it please? :)

**Comment by karanjeets** [comment]
Hi @buggtb 

All done. OODT-885 (https://issues.apache.org/jira/browse/OODT-885) has been raised for the same. Shall I resolve it as well or it will be after merge ?

**Comment by buggtb** [comment]
As I have no idea what the commit is really about I'll leave the PR closing to Chris or someone else, but that looks much better, thanks!

**Comment by lewismc** [comment]
Can you give an example of the RegEx which is passed into this Comparator please? e.g. some XML. What do you expect? What would the results be ? Thanks @karanjeets

**Comment by buggtb** [comment]
One day we might even ask for unit tests ;)

**Comment by karanjeets** [comment]
Sure. Here are the details:

* The Comparator expects two arguments - File object and a regular expression (compare item).
* If all the below three conditions are met, then return **0**, else **1**:
  * Regular Expression shouldn't be NULL.
  * Regular Expression shouldn't be an empty string.
  * File's absolute path matches with the regular expression.

**Example**

If we pass the below regular expression, the comparator will return 0 for all the files where its absolute path contains ".svn" and returns 1 otherwise.

```
.*\\.svn.*
```

We are using this Comparator as part of a [DRAT's](https://github.com/chrismattmann/drat) new feature (--exclude) where we exclude processing of all files which contains some regular expression. In short, this feature exclude all files where Comparator returns 0.

**Comment by chrismattmann** [comment]
all, I'm going to commit this tonight if there are no objections.

**Pull request merged**
