### PR TITLE
[OODT-945] Distributed configuration management- CLI and test resource related improvements

### PR DESCRIPTION
**Pull request by IMS94**
Distributed configuration publishing CLI improvements (using CAS-CLI now. previously I was using args4j) and maven-resource-plugin for example and test resource copying as @chrismattmann suggested. 

Also note that previous PR #44 was missing the executable required **(conf-publisher)** to run the configuration publisher CLI due to a problem with gitignore locally (and therefore hasn't been added when I was committing last time)

### CODE REVIEW

**Comment by chrismattmann** [comment]
hey @IMS94 can you squash/rebase your local and then resubmit your PR? I'm getting a bunch of changes that are already there in the remote branch. Try git pull before you rebase.

**Comment by IMS94** [comment]
hey @chrismattmann, Should be ok now?

**Comment by chrismattmann** [comment]
will review tomorrow

**Comment by chrismattmann** [comment]
build passes, all tests pass, and code looks 👍 

committing!

```
[INFO] >>> maven-javadoc-plugin:2.10.3:javadoc (attach-javadocs) > generate-sources @ oodt >>>
[INFO] 
[INFO] <<< maven-javadoc-plugin:2.10.3:javadoc (attach-javadocs) < generate-sources @ oodt <<<
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.3:javadoc (attach-javadocs) @ oodt ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ oodt ---
[INFO] Installing /Users/mattmann/git/oodt/pom.xml to /Users/mattmann/.m2/repository/org/apache/oodt/oodt/1.2-SNAPSHOT/oodt-1.2-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OODT Core .......................................... SUCCESS [  1.465 s]
[INFO] Common Utilities ................................... SUCCESS [ 17.148 s]
[INFO] CAS Command Line Interface ......................... SUCCESS [  4.770 s]
[INFO] OODT - Configuration Management .................... SUCCESS [  5.153 s]
[INFO] Process Control System Input Data Package .......... SUCCESS [  1.305 s]
[INFO] Catalog and Archive Service Generic Multi-valued Metadata Container SUCCESS [  2.218 s]
[INFO] Catalog and Archive File Management Component ...... SUCCESS [02:20 min]
[INFO] Catalog and Archive Resource Management Component .. SUCCESS [ 15.761 s]
[INFO] Catalog and Archive Workflow Management Component .. SUCCESS [ 25.660 s]
[INFO] Catalog and Archive Crawling Framework ............. SUCCESS [ 14.219 s]
[INFO] OODT CAS Curator Single Sign On Security Package ... SUCCESS [  1.307 s]
[INFO] CAS Curation Web Services .......................... SUCCESS [  6.256 s]
[INFO] Process Control System Core Package ................ SUCCESS [ 11.753 s]
[INFO] OODT Wicket Web Components ......................... SUCCESS [  3.793 s]
[INFO] CAS Curation Interface ............................. SUCCESS [  7.610 s]
[INFO] CAS PGE Adaptor Framework .......................... SUCCESS [ 13.339 s]
[INFO] CAS Installer Maven Mojo ........................... SUCCESS [  2.329 s]
[INFO] OODT :: Archetypes :: OpsUI ........................ SUCCESS [  0.821 s]
[INFO] OODT :: Archetypes :: RADiX ........................ SUCCESS [  0.978 s]
[INFO] OODT :: Archetypes ................................. SUCCESS [  0.024 s]
[INFO] CAS File Manager Browser Web App ................... SUCCESS [  7.333 s]
[INFO] CAS Workflow Manager Monitor Web App ............... SUCCESS [  3.690 s]
[INFO] CAS Product Server Web Application ................. SUCCESS [  9.914 s]
[INFO] CAS Workflow REST Services ......................... SUCCESS [  2.872 s]
[INFO] Process Control System Operator Interface Webapp ... SUCCESS [ 11.993 s]
[INFO] OODT Process Control System JAX-RS service layer ... SUCCESS [  4.930 s]
[INFO] Apache OODT ........................................ SUCCESS [  0.019 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:17 min
[INFO] Finished at: 2017-08-09T10:07:27-07:00
[INFO] Final Memory: 107M/1465M
[INFO] ------------------------------------------------------------------------
LMC-053601:oodt mattmann$ 
```
thanks @IMS94

**Pull request merged**
