### PR TITLE
[OODT-1019] Incorrect Log Levels on .level, .FileHandler.level and .ConsoleHandler.level

### PR DESCRIPTION
**Pull request by yasithmilinda**
Most logging levels are set to DEBUG, which is not a specified log level in java.util.Logging
These should be set to one of :
* SEVERE (highest value)
* WARNING
* INFO
* CONFIG
* FINE
* FINER
* FINEST (lowest value)

I've set these log levels to ALL so that it won't show errors when starting up OODT

### CODE REVIEW

**Comment by buggtb** [comment]
Do you not want errors if its starting OODT?

**Comment by yasithmilinda** [comment]
@buggtb, when I said "I've set these log levels to ALL so that it won't show errors when starting up OODT", what I meant is that I fixed the issue which created the following error logs:

Can't set level for java.util.logging.ConsoleHandler
Can't set level for java.util.logging.FileHandler

The reason for this is the log level being set to DEBUG, which is an invalid log level.
I set it to ALL, which is a valid log level.

**Comment by buggtb** [comment]
Ah right @yasithmilinda makes sense. Can you fix the conflicts and we'll merge it?

**Comment by yasithmilinda** [comment]
Hi @buggtb, I fixed the conflicts and it's ready to be merged

**Comment by IMS94** [comment]
@yasithmilinda Thanks for the PR. Merging.

**Pull request merged**
