### PR TITLE
OODT-933: @Deprecate all XMLRPC Code

### PR DESCRIPTION
**Pull request by Cyan3**

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @Cyan3 I think this needs to build off of the develop branch IIRC. The jump for implementation of AvroRPC (and the other significant improvements) have been discussed in conversation to justify the move to the 2.X branch. I've not checked the branches in a while so apologies if this is incorrect. 

@buggtb is my statement true?

**Comment by chrismattmann** [comment]
yeah there is a conflict here. However I believe master is also compatible with this. @lewismc @buggtb

**Comment by buggtb** [comment]
Master got the lucene upgrade but not the 2.x breaking changes they live on
https://github.com/apache/oodt/tree/development

--------------

Director Meteorite.bi - Saiku Analytics Founder
Tel: +44(0)5603641316

(Thanks to the Saiku community we reached our Kickstart
<http://kickstarter.com/projects/2117053714/saiku-reporting-interactive-report-designer/>
goal, but you can always help by sponsoring the project
<http://www.meteorite.bi/products/saiku/sponsorship>)

**Comment by lewismc** [comment]
@buggtb can you direct me to the Lucene diff in 1.X? I will try to forward port at some stage.

**Comment by chrismattmann** [comment]
team should we merge this? @lewismc @buggtb @Cyan3

**Comment by lewismc** [comment]
Here my opinion as to what needs to be done here
 * resolve conflicting files
 * check out branch at https://github.com/lewismc/oodt/tree/development, I forwarded ported everything from master on to this branch... tests currently fail however it currently represents all of the AvroRPC work we did a while back as well as absolutely everything on master branch. I can verify this as I did it all manually. i suggest that we stabalize this branch. For ease, I created a PR at https://github.com/apache/oodt/pull/46 so you can see the proposed updated to 'development' branch
 * Come back here and make an attempt to merge this into 'development'. AFAIK, 'development' is where we should be putting in the work is this correct @buggtb ?

**Comment by chrismattmann** [comment]
perfect let's do that @lewismc so we can get the AvroRPC stuff in there and just be done with it then stablize

**Comment by lewismc** [comment]
ack, I'll see what I can do about failing tests over at #46

**Comment by buggtb** [comment]
@lewismc yeah shunt it over to development and it'll be good, thats where the ZK stuff will go shortly.

**Pull request merged**
