### PR TITLE
[OODT-978] Fix for Crawler Launcher hanging even after ingesting all the files (when avro fm client is used)

### PR DESCRIPTION
**Pull request by IMS94**

### CODE REVIEW

**Comment by chrismattmann** [comment]
testing this now locally

**Comment by chrismattmann** [comment]
@IMS94 I get an error building this:

```
INFO: Loading workflow context metadata...
Tests run: 15, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 1.242 sec <<< FAILURE! - in org.apache.oodt.cas.pge.TestPGETaskInstance
testCreatePgeConfig(org.apache.oodt.cas.pge.TestPGETaskInstance)  Time elapsed: 0.01 sec  <<< ERROR!
java.io.IOException: Failed to build PgeConfig : Failed to parse value: /var/folders/n5/1d_k3z4s2293q8ntx_n8sw54mm5n_8/T/3ea2e425-c368-4fc3-b73b-fe45724a17b5/pgeConfig.xml
	at java.net.URL.<init>(URL.java:532)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.apache.oodt.cas.pge.util.XmlHelper.fillIn(XmlHelper.java:444)
	at org.apache.oodt.cas.pge.util.XmlHelper.fillIn(XmlHelper.java:438)
	at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:58)
	at org.apache.oodt.cas.pge.PGETaskInstance.createPgeConfig(PGETaskInstance.java:218)
	at org.apache.oodt.cas.pge.TestPGETaskInstance.testCreatePgeConfig(TestPGETaskInstance.java:260)

Running org.apache.oodt.cas.pge.metadata.TestPgeMetadata
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.oodt.cas.pge.metadata.TestPgeMetadata
Running org.apache.oodt.cas.pge.metadata.TestPgeTaskMetKeys
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.oodt.cas.pge.metadata.TestPgeTaskMetKeys

Results :

Tests in error: 
  TestXmlHelper.testGetImports:52 » PGE Failed to parse value: blank
  TestXmlHelper.testGetNamespace:65 » PGE Failed to parse value: blank
  TestXmlFilePgeConfigBuilder.testBuild:54 » IO Failed to build PgeConfig : Fail...
  TestPGETaskInstance.testCreatePgeConfig:260 » IO Failed to build PgeConfig : F...

Tests run: 31, Failures: 0, Errors: 4, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OODT Core .......................................... SUCCESS [  3.146 s]
[INFO] Common Utilities ................................... SUCCESS [ 27.736 s]
[INFO] CAS Command Line Interface ......................... SUCCESS [  6.426 s]
[INFO] OODT - Configuration Management .................... SUCCESS [ 23.711 s]
[INFO] Process Control System Input Data Package .......... SUCCESS [  2.284 s]
[INFO] Catalog and Archive Service Generic Multi-valued Metadata Container SUCCESS [  3.407 s]
[INFO] Catalog and Archive File Management Component ...... SUCCESS [03:50 min]
[INFO] Catalog and Archive Resource Management Component .. SUCCESS [ 33.547 s]
[INFO] Catalog and Archive Workflow Management Component .. SUCCESS [ 42.013 s]
[INFO] Catalog and Archive Crawling Framework ............. SUCCESS [ 26.329 s]
[INFO] OODT CAS Curator Single Sign On Security Package ... SUCCESS [  2.354 s]
[INFO] CAS Curation Web Services .......................... SUCCESS [ 11.634 s]
[INFO] Process Control System Core Package ................ SUCCESS [ 20.501 s]
[INFO] OODT Wicket Web Components ......................... SUCCESS [  6.201 s]
[INFO] CAS Curation Interface ............................. SUCCESS [ 18.657 s]
[INFO] CAS PGE Adaptor Framework .......................... FAILURE [  7.536 s]
[INFO] CAS Installer Maven Mojo ........................... SKIPPED
[INFO] OODT :: Archetypes :: OpsUI ........................ SKIPPED
[INFO] OODT :: Archetypes :: RADiX ........................ SKIPPED
[INFO] OODT :: Archetypes ................................. SKIPPED
[INFO] CAS File Manager Browser Web App ................... SKIPPED
[INFO] CAS Workflow Manager Monitor Web App ............... SKIPPED
[INFO] CAS Product Server Web Application ................. SKIPPED
[INFO] CAS Workflow REST Services ......................... SKIPPED
[INFO] Process Control System Operator Interface Webapp ... SKIPPED
[INFO] OODT Process Control System JAX-RS service layer ... SKIPPED
[INFO] Apache OODT ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:46 min
[INFO] Finished at: 2018-05-17T10:35:12-07:00
[INFO] Final Memory: 116M/1554M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project cas-pge: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/mattmann/git/oodt/pge/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cas-pge
nonas:oodt mattmann$ 

```

Any ideas?

**Comment by IMS94** [comment]
@chrismattmann I will look at that. Seems like this is not related to my changes. Let's see.

**Comment by chrismattmann** [comment]
@IMS94 I think you are right. In fact I think it's related to @lewismc and the update for  OODT-976 in #60

**Comment by IMS94** [comment]
@chrismattmann  Can you check now?

**Comment by chrismattmann** [comment]
nice one @IMS94 I will pull and test now.

**Comment by chrismattmann** [comment]
Works great now, I'm going to merge it!

```
[INFO] --- maven-javadoc-plugin:2.10.3:javadoc (attach-javadocs) @ oodt ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ oodt ---
[INFO] Installing /Users/mattmann/git/oodt/pom.xml to /Users/mattmann/.m2/repository/org/apache/oodt/oodt/1.9-SNAPSHOT/oodt-1.9-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OODT Core .......................................... SUCCESS [  4.124 s]
[INFO] Common Utilities ................................... SUCCESS [ 30.957 s]
[INFO] CAS Command Line Interface ......................... SUCCESS [ 12.048 s]
[INFO] OODT - Configuration Management .................... SUCCESS [ 34.007 s]
[INFO] Process Control System Input Data Package .......... SUCCESS [  3.404 s]
[INFO] Catalog and Archive Service Generic Multi-valued Metadata Container SUCCESS [  4.103 s]
[INFO] Catalog and Archive File Management Component ...... SUCCESS [03:58 min]
[INFO] Catalog and Archive Resource Management Component .. SUCCESS [ 31.632 s]
[INFO] Catalog and Archive Workflow Management Component .. SUCCESS [ 41.087 s]
[INFO] Catalog and Archive Crawling Framework ............. SUCCESS [ 28.410 s]
[INFO] OODT CAS Curator Single Sign On Security Package ... SUCCESS [  1.701 s]
[INFO] CAS Curation Web Services .......................... SUCCESS [ 11.687 s]
[INFO] Process Control System Core Package ................ SUCCESS [ 19.636 s]
[INFO] OODT Wicket Web Components ......................... SUCCESS [  6.191 s]
[INFO] CAS Curation Interface ............................. SUCCESS [ 16.762 s]
[INFO] CAS PGE Adaptor Framework .......................... SUCCESS [ 27.703 s]
[INFO] CAS Installer Maven Mojo ........................... SUCCESS [  6.616 s]
[INFO] OODT :: Archetypes :: OpsUI ........................ SUCCESS [  2.411 s]
[INFO] OODT :: Archetypes :: RADiX ........................ SUCCESS [  1.142 s]
[INFO] OODT :: Archetypes ................................. SUCCESS [  0.025 s]
[INFO] CAS File Manager Browser Web App ................... SUCCESS [ 13.762 s]
[INFO] CAS Workflow Manager Monitor Web App ............... SUCCESS [  6.312 s]
[INFO] CAS Product Server Web Application ................. SUCCESS [ 13.493 s]
[INFO] CAS Workflow REST Services ......................... SUCCESS [  5.431 s]
[INFO] Process Control System Operator Interface Webapp ... SUCCESS [ 31.500 s]
[INFO] OODT Process Control System JAX-RS service layer ... SUCCESS [  8.884 s]
[INFO] Apache OODT ........................................ SUCCESS [  0.021 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:02 min
[INFO] Finished at: 2018-05-18T08:58:23-07:00
[INFO] Final Memory: 136M/1566M
[INFO] ------------------------------------------------------------------------
nonas:oodt mattmann$ 

```

**Pull request merged**
