### PR TITLE
[OODT-986] Add OODT NodeJS File Viewer Prototype

### PR DESCRIPTION
**Pull request by NGimhana**
This PR links with the JIRA Issue [OODT-986](https://issues.apache.org/jira/browse/OODT-986)

This PR Contains a sample React based Prototype for OODT File Manager "File Object Viewer" functionality and a sample swagger implementation for API visualisation.

### CODE REVIEW

**Comment by buggtb** [comment]
Thanks @NGimhana 

Few things that stand out at first glance, can you rename react-webapp, react-components? Can you merge your .gitignore with the top level one?

Thanks

Tom

**Comment by buggtb** [comment]
Sorry @NGimhana can you also stick AS2.0 License headers at the top of the files also please.

**Comment by NGimhana** [comment]
Thanks for reviewing @buggtb. 
Added License headers and other suggestions to files.
Extremely Sorry for the unnecessary commits I made.

**Comment by buggtb** [comment]
No problem @NGimhana we can squash it all at merge time anyway...

I just took a look at your .gitignore, can you check it works as it should? The paths look like it wouldn't look in the correct place.

Can you also do something about the output location of the tarball or whatever that stuff on line 134 is, because that clearly wont stand the test of time when it comes to versioning and needs to preferably end up in a target/ build/ or something directory and then get excluded by a wildcard on that directory.

Thanks!

**Comment by NGimhana** [comment]
"Tarball" is used to verify the package will include only the files you intend it to when published.

Run the `npm pack` command locally which will generate a tarball in the working directory, the same way it does for publishing. However that command will not execute automatically when we build the package. So I removed that verification from .gitignore.

However I suggest to run that command inside dist/. Then we can exclude "dist" directory when it comes to versioning.

**Comment by buggtb** [comment]
LGTM, thanks!

**Pull request merged**
