### PR TITLE
OODT-976 Upgrade Apache Tika to 1.18

### PR DESCRIPTION
**Pull request by lewismc**
This PR addresses https://issues.apache.org/jira/browse/OODT-976
It turns out that commons-compress also needed updating. All tests pass locally. 
The Tika 1.18 mime-types.xml file has been copied to every instance of it within OODT.

### CODE REVIEW

**Comment by chrismattmann** [comment]
@lewismc can you test with DRAT? my worry is that some of our unit tests miss the full end to end coverage of DRAT.

**Comment by lewismc** [comment]
Hi @chrismattmann I'm testing with DRAT... quick question though. Is it necessary for us to rename the ```mime-types.xml``` files present in OODT (and updated as part of the PR) to the Tika equivalent e.g. [tika-mimetypes.xml](https://github.com/apache/tika/blob/70ca280f11fe4127df290b8027c6bc1d5180271f/tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml)? It looks like the [freedesktop.org link at presented in MimeTypesReader.java](https://github.com/apache/tika/blob/70ca280f11fe4127df290b8027c6bc1d5180271f/tika-core/src/main/java/org/apache/tika/mime/MimeTypesReader.java#L99) is broken as well...

**Comment by chrismattmann** [comment]
@lewismc great question. I am not sure we need to rename it since I believe it is explicitly identified in the bin/filemgr script as an argument or system property, e.g., [here](https://github.com/apache/oodt/blob/master/filemgr/src/main/resources/filemgr.properties#L137). Also can you submit a pull request in Tika to fix the location of the freedesktop wiki?

**Comment by lewismc** [comment]
> ...I am not sure we need to rename it since I believe it is explicitly identified in the bin/filemgr script as an argument or system property, e.g., here. 

ACK

> ...Also can you submit a pull request in Tika to fix the location of the freedesktop wiki?

Yes will do it at lunch thanks.

**Comment by lewismc** [comment]
@chrismattmann https://github.com/apache/tika/pull/235

**Comment by lewismc** [comment]
@chrismattmann there is an issue in testing this over in DRAT.
OODT 1.2.2 modules use Tika 1.10 and 1.7 dependencies... hence DRAT distribution packages a deployment which inherits the older Tika dependencies transitively. 
We need to upgrade Tika in OODT, as per this PR, test and push a release before we can move forward elsewhere.

**Comment by chrismattmann** [comment]
@lewismc can't you simply monkey patch DRAT to use the new Tika transitively that OODT would install should this PR be merged, and test it and report back? If I get time today I'll try that myself.

**Comment by chrismattmann** [comment]
@IMS94 can you take a look at this? Do tests pass with the upgrade?

**Comment by IMS94** [comment]
@chrismattmann Sure. Will look at this.

**Comment by chrismattmann** [comment]
@IMS94 can you take a look at this?

**Comment by lewismc** [comment]
The recent Tika 1.19.1 VOTE was cancelled due to pending upgrade of PDFBox.
I would like to upgrade to a more recent version of Tika as it has significant improvements over 1.13 which we are using.
I'll go ahead and close this issue then wait for the pending 1.19.1 release before I work on submitting the PR which we can then test.

**Comment by IMS94** [comment]
@lewismc I saw Tika 1.19.1 has been released. It will be great if you can resend this PR with the desired upgrade when you find some free time.

**Pull request closed without merging**
