### PR TITLE
New PR on different branch to get OSGI Bundle creation from OODT packages

### PR DESCRIPTION
**Pull request by buggtb**
As discussed, Moved to a new branch so I can tinker with this over the next few weeks to make sure the OSGI bundles work properly.

### CODE REVIEW

**Comment by chrismattmann** [comment]
@buggtb what's the status of merging this?

**Comment by buggtb** [comment]
Much closer now the new dependency stuff is merged.  I didn't want to have
to redo it. I'll take a look once the kids have been banished

**Comment by buggtb** [comment]
Ran out of time last night, I'll have a look tonight, hopefully the
Spartans vs Wolverines isn't too much of a distraction....

**Comment by chrismattmann** [comment]
Hail to the victors

**Comment by buggtb** [comment]
This is against a branch in the official repo, so i'm going to merge it in, close it and the work off the main repo which will make my life easier as the rest of my dev work is now against branches in the main repo.

**Comment by buggtb** [comment]
Pushed changes to osgi-plugin branch, will tidy up from there.

**Pull request closed without merging**
