### PR TITLE
OODT-975 Upgrade Tomcat in radix

### PR DESCRIPTION
**Pull request by lewismc**
This issue addresses https://issues.apache.org/jira/browse/OODT-975

### CODE REVIEW

**Comment by chrismattmann** [comment]
@lewismc can you please test with DRAT?

**Comment by lewismc** [comment]
@chrismattmann at some stage in the past, the Tomcat dependency in [DRAT's distribution pom.xml](https://github.com/apache/drat/blob/master/distribution/pom.xml#L18) has been manually upgraded as this is much more recent than the version packaged as part of vanilla radix archetype. I did however make a manual Tomcat upgrade in the DRAT source code (PR available at https://github.com/apache/drat/pull/124) along with an OODT upgrade to 1.2.2. All tests looks good and my screenshots substantiate that.

**Comment by lewismc** [comment]
Also, my tests with COAL-SDS mimic the behaviour with DRAT e.g. the upgrade is working.

**Comment by lewismc** [comment]
Would like to upgrade by EoD today unless there are other comments folks. Thanks.

**Comment by chrismattmann** [comment]
@lewismc I'm seeing some errors running `mvn clean install` with Apache OODT and this patch and running the tests.

**Comment by chrismattmann** [comment]
so I was able to get around this by excluding merge commits...and by cherry picking the commit.

**Pull request merged**
